server:
  port: 8001

spring:
  application:
    name: service-common
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud-chatroom?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hsy990712

mybatis:
  mapperLocations: classpath:/mapper/*.xml
  type-aliases-package: com.example.common.entity
