server:
 port: 8081
 servlet:
   context-path: /chatroom
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    name: chatroom
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///chatroom
    username: root
    password: hsy990712
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    initial-size: 2
    max-idle: 10
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-evict-runs-millis: 60000
    min-evictable-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false

